### ISSUE TITLE
Cannot make it working

### ISSUE THREAD

**Issue by honghaoz** [MarcoSero/EditorConfig-Xcode#1]
I followed the instructions but the editor preference is not updated as what specified in `.editorconfig` file. There's no any indicator to show whether the `. editorconfig` is loaded successfully.

Btw, plugin is loaded successfully.

Any help? Thx

**Comment by MarcoSero** [comment]
The best way to check that the plugin is working correctly would probably be to checkout the code and then build and run the plugin as a normal Xcode project. It will run a separate instance of Xcode and you can place a breakpoint in [-[ECEditorConfigPlugin updateSettingsForFileURL:]](https://github.com/MarcoSero/EditorConfig-Xcode/blob/master/EditorConfig/ECEditorConfigPlugin.m#L59) to confirm the config file is found and loaded correctly.

**Comment by MarcoSero** [comment]
Could you please check again now that support for Xcode 7.2 has been added? https://github.com/MarcoSero/EditorConfig-Xcode/pull/2

Thanks!

**Comment by honghaoz** [comment]
Hey Marco, not sure why I cannot build the project. The error message are here:
<img width="1148" alt="screen shot 2016-01-27 at 9 51 59 am" src="https://cloud.githubusercontent.com/assets/3926785/12616979/a1fd5006-c4db-11e5-9b85-6e42c40f1735.png">

Still not working.

**Comment by honghaoz** [comment]
I cannot build the project. Seems like `CMake` was failed
![screen shot 2016-01-27 at 9 58 17 am](https://cloud.githubusercontent.com/assets/3926785/12617185/8193c4c0-c4dc-11e5-9f65-dca66178b102.png)

**Comment by honghaoz** [comment]
nvm, checked editorconfig and fixed those errors

**Comment by honghaoz** [comment]
@MarcoSero Great, it works! I want to create a menu item and show the status of whether the `.editorconfig` file is loaded. I will try on my fork and let you know

**Comment by MarcoSero** [comment]
Great, thanks!
